# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.AsteriskInfo do
  @moduledoc """
  Asterisk system information
  """

  @derive [Poison.Encoder]
  defstruct [
    :"build",
    :"system",
    :"config",
    :"status"
  ]

  @type t :: %__MODULE__{
    :"build" => BuildInfo,
    :"system" => SystemInfo,
    :"config" => ConfigInfo,
    :"status" => StatusInfo
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.AsteriskInfo do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"build", :struct, Asterisk.ARI.Model.BuildInfo, options)
    |> deserialize(:"system", :struct, Asterisk.ARI.Model.SystemInfo, options)
    |> deserialize(:"config", :struct, Asterisk.ARI.Model.ConfigInfo, options)
    |> deserialize(:"status", :struct, Asterisk.ARI.Model.StatusInfo, options)
  end
end

