# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.Bridge do
  @moduledoc """
  The merging of media from one or more channels.  Everyone on the bridge receives the same audio.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"technology",
    :"bridge_type",
    :"bridge_class",
    :"creator",
    :"name",
    :"channels",
    :"video_mode",
    :"video_source_id"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"technology" => String.t,
    :"bridge_type" => String.t,
    :"bridge_class" => String.t,
    :"creator" => String.t,
    :"name" => String.t,
    :"channels" => ListString,
    :"video_mode" => String.t,
    :"video_source_id" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.Bridge do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"channels", :struct, Asterisk.ARI.Model.ListString, options)
  end
end

