# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.BridgeCreated do
  @moduledoc """
  Notification that a bridge has been created.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bridge"
  ]

  @type t :: %__MODULE__{
    :"bridge" => Bridge
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.BridgeCreated do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"bridge", :struct, Asterisk.ARI.Model.Bridge, options)
  end
end

