# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.BridgeVideoSourceChanged do
  @moduledoc """
  Notification that the source of video in a bridge has changed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bridge",
    :"old_video_source_id"
  ]

  @type t :: %__MODULE__{
    :"bridge" => Bridge,
    :"old_video_source_id" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.BridgeVideoSourceChanged do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"bridge", :struct, Asterisk.ARI.Model.Bridge, options)
  end
end

