# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.BridgeBlindTransfer do
  @moduledoc """
  Notification that a blind transfer has occurred.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"channel",
    :"replace_channel",
    :"transferee",
    :"exten",
    :"context",
    :"result",
    :"is_external",
    :"bridge"
  ]

  @type t :: %__MODULE__{
    :"channel" => Channel,
    :"replace_channel" => Channel,
    :"transferee" => Channel,
    :"exten" => String.t,
    :"context" => String.t,
    :"result" => String.t,
    :"is_external" => boolean(),
    :"bridge" => Bridge
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.BridgeBlindTransfer do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"channel", :struct, Asterisk.ARI.Model.Channel, options)
    |> deserialize(:"replace_channel", :struct, Asterisk.ARI.Model.Channel, options)
    |> deserialize(:"transferee", :struct, Asterisk.ARI.Model.Channel, options)
    |> deserialize(:"bridge", :struct, Asterisk.ARI.Model.Bridge, options)
  end
end

