# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.ChannelUnhold do
  @moduledoc """
  A channel initiated a media unhold.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"channel"
  ]

  @type t :: %__MODULE__{
    :"channel" => Channel
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.ChannelUnhold do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"channel", :struct, Asterisk.ARI.Model.Channel, options)
  end
end

