# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.ChannelEnteredBridge do
  @moduledoc """
  Notification that a channel has entered a bridge.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bridge",
    :"channel"
  ]

  @type t :: %__MODULE__{
    :"bridge" => Bridge,
    :"channel" => Channel
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.ChannelEnteredBridge do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"bridge", :struct, Asterisk.ARI.Model.Bridge, options)
    |> deserialize(:"channel", :struct, Asterisk.ARI.Model.Channel, options)
  end
end

