# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.ChannelDtmfReceived do
  @moduledoc """
  DTMF received on a channel.  This event is sent when the DTMF ends. There is no notification about the start of DTMF
  """

  @derive [Poison.Encoder]
  defstruct [
    :"digit",
    :"duration_ms",
    :"channel"
  ]

  @type t :: %__MODULE__{
    :"digit" => String.t,
    :"duration_ms" => Int,
    :"channel" => Channel
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.ChannelDtmfReceived do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"duration_ms", :struct, Asterisk.ARI.Model.Int, options)
    |> deserialize(:"channel", :struct, Asterisk.ARI.Model.Channel, options)
  end
end

