# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.ChannelDialplan do
  @moduledoc """
  Channel changed location in the dialplan.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"channel",
    :"dialplan_app",
    :"dialplan_app_data"
  ]

  @type t :: %__MODULE__{
    :"channel" => Channel,
    :"dialplan_app" => String.t,
    :"dialplan_app_data" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.ChannelDialplan do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"channel", :struct, Asterisk.ARI.Model.Channel, options)
  end
end

