# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.ChannelTalkingFinished do
  @moduledoc """
  Talking is no longer detected on the channel.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"channel",
    :"duration"
  ]

  @type t :: %__MODULE__{
    :"channel" => Channel,
    :"duration" => Int
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.ChannelTalkingFinished do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"channel", :struct, Asterisk.ARI.Model.Channel, options)
    |> deserialize(:"duration", :struct, Asterisk.ARI.Model.Int, options)
  end
end

