# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.ChannelHangupRequest do
  @moduledoc """
  A hangup was requested on the channel.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cause",
    :"soft",
    :"channel"
  ]

  @type t :: %__MODULE__{
    :"cause" => Int,
    :"soft" => boolean(),
    :"channel" => Channel
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.ChannelHangupRequest do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"cause", :struct, Asterisk.ARI.Model.Int, options)
    |> deserialize(:"channel", :struct, Asterisk.ARI.Model.Channel, options)
  end
end

