# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.ConfigTuple do
  @moduledoc """
  A key/value pair that makes up part of a configuration object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"attribute",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"attribute" => String.t,
    :"value" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.ConfigTuple do
  def decode(value, _options) do
    value
  end
end

