# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.ContactInfo do
  @moduledoc """
  Detailed information about a contact on an endpoint.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"uri",
    :"contact_status",
    :"aor",
    :"roundtrip_usec"
  ]

  @type t :: %__MODULE__{
    :"uri" => String.t,
    :"contact_status" => String.t,
    :"aor" => String.t,
    :"roundtrip_usec" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.ContactInfo do
  def decode(value, _options) do
    value
  end
end

