# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.DeviceStateChanged do
  @moduledoc """
  Notification that a device state has changed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"device_state"
  ]

  @type t :: %__MODULE__{
    :"device_state" => DeviceState
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.DeviceStateChanged do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"device_state", :struct, Asterisk.ARI.Model.DeviceState, options)
  end
end

