# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.DeviceState do
  @moduledoc """
  Represents the state of a device.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"state"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"state" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.DeviceState do
  def decode(value, _options) do
    value
  end
end

