# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.DialplanCep do
  @moduledoc """
  Dialplan location (context/extension/priority)
  """

  @derive [Poison.Encoder]
  defstruct [
    :"context",
    :"exten",
    :"priority"
  ]

  @type t :: %__MODULE__{
    :"context" => String.t,
    :"exten" => String.t,
    :"priority" => Integer
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.DialplanCep do
  def decode(value, _options) do
    value
  end
end

