# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.EndpointStateChange do
  @moduledoc """
  Endpoint state changed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"endpoint"
  ]

  @type t :: %__MODULE__{
    :"endpoint" => Endpoint
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.EndpointStateChange do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"endpoint", :struct, Asterisk.ARI.Model.Endpoint, options)
  end
end

