# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.Endpoint do
  @moduledoc """
  An external device that may offer/accept calls to/from Asterisk.  Unlike most resources, which have a single unique identifier, an endpoint is uniquely identified by the technology/resource pair.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"technology",
    :"resource",
    :"state",
    :"channel_ids"
  ]

  @type t :: %__MODULE__{
    :"technology" => String.t,
    :"resource" => String.t,
    :"state" => String.t,
    :"channel_ids" => ListString
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.Endpoint do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"channel_ids", :struct, Asterisk.ARI.Model.ListString, options)
  end
end

