# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.LogChannel do
  @moduledoc """
  Details of an Asterisk log channel
  """

  @derive [Poison.Encoder]
  defstruct [
    :"channel",
    :"type",
    :"status",
    :"configuration"
  ]

  @type t :: %__MODULE__{
    :"channel" => String.t,
    :"type" => String.t,
    :"status" => String.t,
    :"configuration" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.LogChannel do
  def decode(value, _options) do
    value
  end
end

