# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.Mailbox do
  @moduledoc """
  Represents the state of a mailbox.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"old_messages",
    :"new_messages"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"old_messages" => Int,
    :"new_messages" => Int
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.Mailbox do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"old_messages", :struct, Asterisk.ARI.Model.Int, options)
    |> deserialize(:"new_messages", :struct, Asterisk.ARI.Model.Int, options)
  end
end

