# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.Message do
  @moduledoc """
  Base type for errors and events
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"asterisk_id"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t,
    :"asterisk_id" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.Message do
  def decode(value, _options) do
    value
  end
end

