# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.MissingParams do
  @moduledoc """
  Error event sent when required params are missing.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"params"
  ]

  @type t :: %__MODULE__{
    :"params" => ListString
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.MissingParams do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"params", :struct, Asterisk.ARI.Model.ListString, options)
  end
end

