# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.Module do
  @moduledoc """
  Details of an Asterisk module
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"description",
    :"use_count",
    :"status",
    :"support_level"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"description" => String.t,
    :"use_count" => Int,
    :"status" => String.t,
    :"support_level" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.Module do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"use_count", :struct, Asterisk.ARI.Model.Int, options)
  end
end

