# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.PeerStatusChange do
  @moduledoc """
  The state of a peer associated with an endpoint has changed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"endpoint",
    :"peer"
  ]

  @type t :: %__MODULE__{
    :"endpoint" => Endpoint,
    :"peer" => Peer
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.PeerStatusChange do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"endpoint", :struct, Asterisk.ARI.Model.Endpoint, options)
    |> deserialize(:"peer", :struct, Asterisk.ARI.Model.Peer, options)
  end
end

