# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.Peer do
  @moduledoc """
  Detailed information about a remote peer that communicates with Asterisk.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"peer_status",
    :"cause",
    :"address",
    :"port",
    :"time"
  ]

  @type t :: %__MODULE__{
    :"peer_status" => String.t,
    :"cause" => String.t,
    :"address" => String.t,
    :"port" => String.t,
    :"time" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.Peer do
  def decode(value, _options) do
    value
  end
end

