# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.SetId do
  @moduledoc """
  Effective user/group id
  """

  @derive [Poison.Encoder]
  defstruct [
    :"user",
    :"group"
  ]

  @type t :: %__MODULE__{
    :"user" => String.t,
    :"group" => String.t
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.SetId do
  def decode(value, _options) do
    value
  end
end

