# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.Sound do
  @moduledoc """
  A media file that may be played back.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"text",
    :"formats"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"text" => String.t,
    :"formats" => ListFormatLangPair
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.Sound do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"formats", :struct, Asterisk.ARI.Model.ListFormatLangPair, options)
  end
end

