# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.StatusInfo do
  @moduledoc """
  Info about Asterisk status
  """

  @derive [Poison.Encoder]
  defstruct [
    :"startup_time",
    :"last_reload_time"
  ]

  @type t :: %__MODULE__{
    :"startup_time" => DateTime,
    :"last_reload_time" => DateTime
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.StatusInfo do
  def decode(value, _options) do
    value
  end
end

