# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Model.TextMessage do
  @moduledoc """
  A text message.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"from",
    :"to",
    :"body",
    :"variables"
  ]

  @type t :: %__MODULE__{
    :"from" => String.t,
    :"to" => String.t,
    :"body" => String.t,
    :"variables" => ListTextMessageVariable
  }
end

defimpl Poison.Decoder, for: Asterisk.ARI.Model.TextMessage do
  import Asterisk.ARI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"variables", :struct, Asterisk.ARI.Model.ListTextMessageVariable, options)
  end
end

