# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Api.ApiDocsmailboxesFormat do
  @moduledoc """
  API calls for all endpoints tagged `ApiDocsmailboxesFormat`.
  """

  alias Asterisk.ARI.Connection
  import Asterisk.ARI.RequestBuilder


  @doc """
  Destroy a mailbox.

  ## Parameters

  - connection (Asterisk.ARI.Connection): Connection to server
  - mailbox_name (String.t): Name of the mailbox
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec delete(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def delete(connection, mailbox_name, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/mailboxes/#{mailbox_name}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Retrieve the current state of a mailbox.

  ## Parameters

  - connection (Asterisk.ARI.Connection): Connection to server
  - mailbox_name (String.t): Name of the mailbox
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec get(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def get(connection, mailbox_name, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/mailboxes/#{mailbox_name}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  List all mailboxes.

  ## Parameters

  - connection (Asterisk.ARI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec list(Tesla.Env.client, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def list(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/mailboxes")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Change the state of a mailbox. (Note - implicitly creates the mailbox).

  ## Parameters

  - connection (Asterisk.ARI.Connection): Connection to server
  - mailbox_name (String.t): Name of the mailbox
  - old_messages (integer()): Count of old messages in the mailbox
  - new_messages (integer()): Count of new messages in the mailbox
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec update(Tesla.Env.client, String.t, integer(), integer(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def update(connection, mailbox_name, old_messages, new_messages, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/mailboxes/#{mailbox_name}")
    |> add_param(:query, :"oldMessages", old_messages)
    |> add_param(:query, :"newMessages", new_messages)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end
end
