# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Asterisk.ARI.Connection do
  @moduledoc """
  Handle Tesla connections for Asterisk.ARI.
  """

  use Tesla

  # Add any middleware here (authentication)
  plug Tesla.Middleware.BaseUrl, "http://192.168.0.240:8088/ari"
  plug Tesla.Middleware.Headers, [{"User-Agent", "Elixir"}]
  plug Tesla.Middleware.EncodeJson

  @doc """
  Configure an authless client connection

  # Returns

  Tesla.Env.client
  """
  @spec new() :: Tesla.Env.client
  def new do
    Tesla.client([])
  end
end
